# ── Project ───────────────────────────────────────────────
sonar.projectKey=touchbase-frontend
sonar.projectName=TouchBase Frontend
sonar.projectVersion=1.0

# ── Sources ───────────────────────────────────────────────
sonar.sources=src
sonar.exclusions=\
  src/test/**,\
  node_modules/**,\
  dist/**,\
  coverage/**,\
  src/main.jsx,\
  **/*.css

sonar.tests=src/test
sonar.test.inclusions=**/*.test.jsx,**/*.test.js

# ── Coverage ──────────────────────────────────────────────
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# ── Server ────────────────────────────────────────────────
sonar.host.url=http://localhost:9000
sonar.login=sqp_4302037b76dddc30223de61fdf824bc20f0804b3

# ── Encoding ──────────────────────────────────────────────
sonar.sourceEncoding=UTF-8